# Generated by Django 2.1.2 on 2018-10-27 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discovery_frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=30, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('contactNumber1', models.IntegerField(null=True)),
                ('contactNumber2', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discovery_frontend.ContactDetail'),
        ),
    ]
