# Generated by Django 2.1.2 on 2018-10-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery_frontend', '0002_auto_20181027_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='keyWords',
            field=models.ManyToManyField(help_text='tags', to='discovery_frontend.KeyWord'),
        ),
        migrations.AddField(
            model_name='location',
            name='possibleActivities',
            field=models.CharField(default='test', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
