# Generated by Django 2.1.2 on 2018-10-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('contactNumber1', models.IntegerField(blank=True, null=True)),
                ('contactNumber2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discovery_api.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('free', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=100, null=True)),
                ('possibleActivities', models.CharField(max_length=1000)),
                ('activities', models.ManyToManyField(help_text='tags', to='discovery_api.Activity')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discovery_api.ContactDetail')),
                ('keyWords', models.ManyToManyField(help_text='tags', to='discovery_api.KeyWord')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=20)),
                ('reviewDescription', models.CharField(max_length=1000)),
                ('locationID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='discovery_api.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Warnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discovery_api.Category')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='warnings',
            field=models.ManyToManyField(help_text='warnings', to='discovery_api.Warnings'),
        ),
        migrations.AddField(
            model_name='activity',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discovery_api.Category'),
        ),
    ]
